# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Collections
collections:
  docs:
    output: true

# Setup
title:            SensorHub
tagline:          'Software for building smart sensor networks'
description:      'Technical Docs and Blog for the OpenSensorHub Project'
url:              http://www.opensensorhub.org
baseurl:          "/"

author:
  name:           'Sensia Software'
  url:            http://www.sensiasoftware.com

paginate:         5

# Custom vars
version:          1.0-beta

github:
  repo:           https://github.com/sensiasoft/sensorhub
